name: Ilmavaatlus

on:
  schedule:
    - cron: '0 5 * * *'
  workflow_dispatch:  # allows manual triggering

jobs:
  run-ilm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
      - name: Install packages
        run: Rscript -e "install.packages(c('httr','jsonlite','dplyr','tidyr','ggplot2','plotly','htmlwidgets'))"
      - name: Run script
        env:
          TG_TOKEN: ${{ secrets.TG_TOKEN }}
          TG_CHAT: ${{ secrets.TG_CHAT }}
        run: Rscript ilm.R
